output_format: "delta"
accelerator: gpu
temp_path: /dbfs/tmp

metric: smape
scoring_model_stage: Production
selection_metric: smape_eval
backtest_retrain: false

resample: false
train_predict_ratio: 4
freq: D

tuning_enabled: false
tuning_max_trials: 16
tuning_parallelism: 4
tuning_retrain: false
tuning_distributed: true
tuning_max_epochs: 10
tuning_max_context_len: 40

dynamic_reals:

static_features:
  #- State

dynamic_future:
  #- Open
  #- Promo
  #- DayOfWeek

dynamic_historical:

active_models:
  - StatsForecastAutoArima
  - StatsForecastAutoETS
  - StatsForecastAutoCES
  - StatsForecastAutoTheta
  - RFableArima
  - RFableETS
  - RDynamicHarmonicRegression
  - RFableNNETAR
  - RFableEnsemble
  - GluonTSNBEATS
  - GluonTSNBEATSTunable
  - GluonTSDeepAR
  - GluonTSSeasonalNaive
  - GluonTSTorchDeepAR
  - GluonTSProphet
  - NeuralForecastRNN
  - NeuralForecastLSTM
  - NeuralForecastNBEATSx
  - NeuralForecastNHITS
  - NeuralForecastAutoRNN
  - NeuralForecastAutoLSTM
  - NeuralForecastAutoNBEATSx
  - NeuralForecastAutoNHITS

#Here we can override hyperparameters for built-in models
models:

  GluonTSNBEATS:
    epochs: 15

  GluonTSDeepAR:
    epochs: 10
    context_length: 30
    batch_size: 64

  GluonTSTorchDeepAR:
    epochs: 15
    context_length: 30
    batch_size: 64
    
  GluonTSProphet:
    model_spec:
      yearly_seasonality: 'auto'
      weekly_seasonality: 'auto'
      daily_seasonality: false

  StatsForecastAutoArima:
    model_spec:
      season_length: 7
      approximation:
      level:

  StatsForecastAutoETS:
    model_spec:
      season_length: 7
      model: "ZNZ"

  StatsForecastAutoCES:
    model_spec:
      season_length: 7
      model: "Z"

  StatsForecastAutoTheta:
    model_spec:
      season_length: 7
      decomposition_type: "multiplicative"

  StatsForecastBaselineWindowAverage:
    model_spec:
      window_size: 7

  StatsForecastBaselineSeasonalWindowAverage:
    model_spec:
      season_length: 7
      window_size: 7

  StatsForecastBaselineSeasonalNaive:
    model_spec:
      season_length: 7

  RFableArima:
    model_spec:
      season_length: 7

  RFableETS:
    model_spec:
      season_length: 7

  RFableNNETAR:
    model_spec:
      season_length: 7

  RDynamicHarmonicRegression:
    model_spec:
      fourier_terms:
        - weekly:
            season_length: 7
            fourier_order: 3
        - yearly:
            season_length: 52
            fourier_order: 5

  RFableEnsemble:
    model_spec:
      models:
        - model:
            name: RFableArima
            model_spec:
              season_length: 7
        - model:
            name: RFableETS
            model_spec:
              season_length: 7
        - model:
            name: RFableNNETAR
            model_spec:
              season_length: 7
