# Databricks notebook source
# MAGIC %md
# MAGIC # MMF GPU Models
# MAGIC Auto-generated by mmf-agent.

# COMMAND ----------

# MAGIC %pip install "mmf_sa{pip_extras} @ git+https://github.com/databricks-industry-solutions/many-model-forecasting.git@v0.1.2" --quiet

# COMMAND ----------

# MAGIC %restart_python

# COMMAND ----------

catalog = "{catalog}"
schema = "{schema}"
train_table = "{train_table}"
freq = "{freq}"
prediction_length = {prediction_length}
backtest_length = {backtest_length}
stride = {stride}
metric = "{metric}"
active_models = {active_models}
group_id = "{group_id}"
date_col = "{date_col}"
target = "{target}"

# COMMAND ----------

from mmf_sa import run_forecast

user = spark.sql("SELECT current_user() AS user").collect()[0]["user"]

run_forecast(
    spark=spark,
    train_data=catalog + "." + schema + "." + train_table,
    scoring_data=catalog + "." + schema + "." + train_table,
    scoring_output=catalog + "." + schema + ".mmf_scoring_output",
    evaluation_output=catalog + "." + schema + ".mmf_evaluation_output",
    group_id=group_id,
    date_col=date_col,
    target=target,
    freq=freq,
    prediction_length=prediction_length,
    backtest_length=backtest_length,
    stride=stride,
    metric=metric,
    train_predict_ratio=1,
    data_quality_check=True,
    resample=False,
    active_models=active_models,
    experiment_path="/Users/" + user + "/mmf/" + catalog + "_" + schema,
    use_case_name=catalog + "_" + schema,
    accelerator="gpu",
)